create table Space (
	Space_ID INT,
	Space_Name VARCHAR(50),
	Address VARCHAR(50),
	Description TEXT,
	Type VARCHAR(13),
	Price DECIMAL(6,2),
	Availability VARCHAR(2),
	Owner_ID INT
);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (1, 'O''Reilly-Stoltenberg', '7095 Oak Trail', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 'Technology', 711.49, 'ye', 1);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (2, 'Rau Group', '38554 Erie Center', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 'Music', 834.59, 'ye', 2);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (3, 'Berge, Kulas and O''Hara', '2 Corscot Street', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 'Music', 651.03, 'ye', 3);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (4, 'Ward LLC', '16 Oak Valley Drive', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'Culinary Arts', 468.98, 'ye', 4);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (5, 'Schoen-Langosh', '6170 Elmside Trail', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 'Culinary Arts', 843.97, 'ye', 5);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (6, 'Lemke, Volkman and Schulist', '6 2nd Pass', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'Technology', 973.03, 'ye', 6);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (7, 'McCullough and Sons', '8635 Doe Crossing Parkway', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 'Music', 289.22, 'ye', 7);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (8, 'Cassin-Lehner', '45873 Wayridge Road', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 'Music', 727.59, 'ye', 8);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (9, 'Doyle, Tillman and Shields', '77570 Sauthoff Crossing', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 'Music', 399.79, 'ye', 9);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (10, 'Hackett, McGlynn and Block', '141 Johnson Pass', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 'Music', 4.35, 'ye', 10);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (11, 'Terry Inc', '40 Lighthouse Bay Terrace', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 'Art', 861.55, 'ye', 11);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (12, 'Lowe, Hartmann and Funk', '6457 Service Drive', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 'Art', 152.06, 'ye', 12);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (13, 'Kuhn and Sons', '917 Melvin Parkway', 'Fusce consequat. Nulla nisl. Nunc nisl.', 'Music', 598.72, 'ye', 13);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (14, 'Senger-Gleichner', '36 Meadow Vale Circle', 'Fusce consequat. Nulla nisl. Nunc nisl.', 'Technology', 167.11, 'ye', 14);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (15, 'Larkin, Crist and Reichert', '01624 Calypso Trail', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 'Art', 156.41, 'ye', 15);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (16, 'Kub Inc', '3114 Village Drive', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'Culinary Arts', 873.72, 'ye', 16);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (17, 'Jenkins Inc', '7 Dixon Point', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'Technology', 225.95, 'ye', 17);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (18, 'Paucek, Botsford and Moore', '0 Monterey Center', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'Science', 617.1, 'ye', 18);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (19, 'Heaney-King', '8 Ohio Road', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 'Science', 305.36, 'ye', 19);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (20, 'Hintz-Tremblay', '853 Holy Cross Place', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 'Culinary Arts', 459.67, 'ye', 20);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (21, 'Gottlieb LLC', '0 Ohio Parkway', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 'Science', 191.62, 'ye', 21);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (22, 'Walker-Gottlieb', '2 Sachtjen Circle', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 'Art', 608.29, 'ye', 22);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (23, 'Wintheiser, Mueller and Heller', '92 Coolidge Way', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 'Music', 333.78, 'ye', 23);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (24, 'O''Reilly, Breitenberg and Skiles', '2988 Bartelt Hill', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'Science', 6.42, 'ye', 24);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (25, 'Strosin, Satterfield and Labadie', '65 Stang Terrace', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 'Science', 823.22, 'ye', 25);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (26, 'Schaden Inc', '902 Center Trail', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'Technology', 866.03, 'ye', 26);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (27, 'Langosh, Watsica and Wyman', '3066 Lukken Trail', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 'Science', 93.31, 'ye', 27);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (28, 'Paucek-Vandervort', '9 Ruskin Pass', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'Technology', 169.42, 'ye', 28);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (29, 'Hermann-Mosciski', '7 Larry Parkway', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 'Music', 356.56, 'ye', 29);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (30, 'Windler, Halvorson and Lehner', '559 Artisan Place', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'Art', 742.93, 'ye', 30);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (31, 'Block-Roob', '81502 Sachs Circle', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'Culinary Arts', 346.44, 'ye', 31);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (32, 'Champlin, Muller and Hand', '2392 Blackbird Hill', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 'Art', 328.39, 'ye', 32);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (33, 'Prohaska-Hoppe', '60 Fremont Crossing', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 'Technology', 521.02, 'ye', 33);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (34, 'Haag-Larkin', '5123 Browning Crossing', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 'Science', 989.07, 'ye', 34);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (35, 'Langosh Group', '3 Debra Street', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'Music', 639.13, 'ye', 35);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (36, 'Orn, Fadel and Murazik', '1261 Haas Terrace', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'Science', 59.67, 'ye', 36);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (37, 'Lubowitz and Sons', '18 Pine View Alley', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 'Music', 957.56, 'ye', 37);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (38, 'Kub, Reynolds and Bruen', '72 Village Drive', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 'Technology', 536.45, 'ye', 38);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (39, 'Welch, Rippin and Sanford', '196 Tomscot Way', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'Art', 146.4, 'ye', 39);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (40, 'Ruecker-Hamill', '8 Schmedeman Street', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 'Science', 176.72, 'ye', 40);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (41, 'O''Conner-Romaguera', '35382 Artisan Crossing', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 'Art', 345.82, 'ye', 41);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (42, 'Torphy, Waters and Von', '04218 Graedel Plaza', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 'Culinary Arts', 70.02, 'ye', 42);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (43, 'Ritchie-Little', '9 Moland Road', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 'Culinary Arts', 494.54, 'ye', 43);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (44, 'Mohr-Hegmann', '646 Grover Hill', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'Technology', 100.69, 'ye', 44);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (45, 'Larkin-Schmeler', '11666 International Court', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 'Science', 901.55, 'ye', 45);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (46, 'Considine, Paucek and Kuhic', '7 Steensland Road', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 'Culinary Arts', 882.27, 'ye', 46);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (47, 'Kunze LLC', '6010 Jenifer Avenue', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 'Art', 54.22, 'ye', 47);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (48, 'Fritsch-Hoppe', '975 Laurel Plaza', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 'Music', 46.98, 'ye', 48);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (49, 'Rohan LLC', '7979 Starling Plaza', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 'Science', 204.55, 'ye', 49);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (50, 'Bauch, Koch and Muller', '0 Golden Leaf Plaza', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'Culinary Arts', 41.61, 'ye', 50);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (51, 'Halvorson-Kuhic', '13 Mendota Avenue', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 'Science', 298.11, 'ye', 51);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (52, 'Veum-Thiel', '22264 Muir Drive', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 'Music', 483.22, 'ye', 52);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (53, 'Trantow LLC', '4539 Charing Cross Park', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'Science', 797.13, 'ye', 53);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (54, 'Lang-Kshlerin', '53564 Superior Place', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 'Art', 601.08, 'ye', 54);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (55, 'Cummings-Sanford', '025 Barby Drive', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 'Culinary Arts', 287.51, 'ye', 55);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (56, 'Koepp, Franecki and Stoltenberg', '435 Red Cloud Road', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 'Science', 887.66, 'ye', 56);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (57, 'Bartoletti, Sanford and Collins', '773 Mallory Center', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 'Technology', 800.72, 'ye', 57);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (58, 'VonRueden Inc', '31 Sundown Center', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'Art', 740.73, 'ye', 58);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (59, 'Christiansen, Cremin and Koepp', '9514 6th Court', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 'Science', 700.93, 'ye', 59);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (60, 'Huel-Wehner', '83606 Milwaukee Avenue', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 'Music', 837.41, 'ye', 60);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (61, 'Purdy LLC', '1126 Vahlen Road', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 'Technology', 236.45, 'ye', 61);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (62, 'Torphy, Buckridge and Moen', '65 Farragut Terrace', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'Music', 678.44, 'ye', 62);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (63, 'McDermott LLC', '0392 Mitchell Street', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 'Music', 701.06, 'ye', 63);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (64, 'Harber-Lang', '9 Memorial Park', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'Science', 631.82, 'ye', 64);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (65, 'Schmidt-Langworth', '445 Prairieview Circle', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 'Art', 283.05, 'ye', 65);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (66, 'Hudson Group', '23 Longview Avenue', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 'Culinary Arts', 914.92, 'ye', 66);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (67, 'Lesch-Legros', '363 Westerfield Plaza', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 'Science', 103.07, 'ye', 67);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (68, 'Runte LLC', '322 Packers Pass', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 'Culinary Arts', 223.47, 'ye', 68);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (69, 'Pfeffer Group', '11 Sachs Parkway', 'In congue. Etiam justo. Etiam pretium iaculis justo.', 'Technology', 942.48, 'ye', 69);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (70, 'Rippin Inc', '923 Carioca Center', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 'Culinary Arts', 534.8, 'ye', 70);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (71, 'Sanford, Rath and Emard', '7589 Acker Plaza', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 'Technology', 587.75, 'ye', 71);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (72, 'Treutel, Dickens and Dickens', '496 Summer Ridge Hill', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 'Technology', 517.34, 'ye', 72);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (73, 'Gibson, Wintheiser and Dach', '4148 Veith Crossing', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 'Art', 72.37, 'ye', 73);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (74, 'Hodkiewicz, Terry and O''Conner', '2450 Sunfield Avenue', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 'Science', 471.93, 'ye', 74);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (75, 'Littel and Sons', '4 Dixon Circle', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'Art', 889.76, 'ye', 75);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (76, 'Littel-Macejkovic', '59661 Moulton Terrace', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'Science', 222.01, 'ye', 76);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (77, 'Rogahn, Breitenberg and Carter', '5 Northview Hill', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 'Science', 457.21, 'ye', 77);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (78, 'Rice LLC', '85 Granby Hill', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 'Music', 408.71, 'ye', 78);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (79, 'Marquardt-Armstrong', '6158 Declaration Center', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 'Technology', 234.62, 'ye', 79);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (80, 'Kunde-Wuckert', '9264 Doe Crossing Court', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 'Art', 793.75, 'ye', 80);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (81, 'Treutel Group', '51 Surrey Center', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 'Culinary Arts', 996.4, 'ye', 81);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (82, 'Bogan-Zieme', '30 Old Gate Trail', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'Science', 98.06, 'ye', 82);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (83, 'Kling LLC', '31 Acker Place', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 'Technology', 349.31, 'ye', 83);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (84, 'Hegmann, Boyle and Aufderhar', '37504 Bunting Place', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 'Technology', 522.69, 'ye', 84);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (85, 'Borer-Ferry', '1579 Eagle Crest Place', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 'Art', 274.81, 'ye', 85);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (86, 'Kozey-Mann', '820 Twin Pines Junction', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 'Technology', 282.72, 'ye', 86);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (87, 'Koss LLC', '3 Victoria Circle', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 'Music', 915.68, 'ye', 87);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (88, 'Schaefer Group', '6706 Ilene Drive', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 'Music', 745.96, 'ye', 88);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (89, 'Frami-Kshlerin', '6789 7th Alley', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 'Culinary Arts', 381.59, 'ye', 89);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (90, 'Lehner and Sons', '384 Macpherson Drive', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 'Music', 732.45, 'ye', 90);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (91, 'Gislason, Murphy and Greenholt', '347 Hovde Avenue', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 'Science', 857.18, 'ye', 91);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (92, 'MacGyver, Larkin and Weber', '49 High Crossing Park', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 'Music', 198.5, 'ye', 92);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (93, 'Kerluke, Nolan and Skiles', '9 Trailsway Court', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 'Art', 43.6, 'ye', 93);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (94, 'Schmidt and Sons', '77599 Chive Park', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 'Technology', 266.91, 'ye', 94);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (95, 'Barrows Group', '16817 Glacier Hill Road', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'Culinary Arts', 772.77, 'ye', 95);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (96, 'Hintz-Keeling', '53406 School Alley', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 'Technology', 46.59, 'ye', 96);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (97, 'Morissette Group', '746 American Ash Pass', 'In congue. Etiam justo. Etiam pretium iaculis justo.', 'Science', 896.2, 'ye', 97);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (98, 'Collins-Heaney', '83204 Kipling Center', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 'Art', 879.77, 'ye', 98);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (99, 'Homenick-Koch', '23 Summit Center', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 'Culinary Arts', 27.18, 'ye', 99);
insert into Space (Space_ID, Space_Name, Address, Description, Type, Price, Availability, Owner_ID) values (100, 'Prosacco, McCullough and Pagac', '899 Susan Plaza', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 'Technology', 737.19, 'ye', 100);

INSERT INTO your_table_name (Pic_ID, Pic_URL, UploadDate, Caption, Space_ID) VALUES
(1, '1.jpg', '2024-04-28', 'Caption for image 1', 1),
(2, '2.jpg', '2024-04-28', 'Caption for image 2', 2),
(3, '3.jpg', '2024-04-28', 'Caption for image 3', 3),
(4, '4.jpg', '2024-04-28', 'Caption for image 4', 4),
(5, '5.jpg', '2024-04-28', 'Caption for image 5', 5),
(6, '6.jpg', '2024-04-28', 'Caption for image 6', 6),
(7, '7.jpg', '2024-04-28', 'Caption for image 7', 7),
(8, '8.jpg', '2024-04-28', 'Caption for image 8', 8),
(9, '9.jpg', '2024-04-28', 'Caption for image 9', 9),
(10, '10.jpg', '2024-04-28', 'Caption for image 10', 10),
(11, '11.jpg', '2024-04-28', 'Caption for image 11', 11),
(12, '12.jpg', '2024-04-28', 'Caption for image 12', 12),
(13, '13.jpg', '2024-04-28', 'Caption for image 13', 13),
(14, '14.jpg', '2024-04-28', 'Caption for image 14', 14),
(15, '15.jpg', '2024-04-28', 'Caption for image 15', 15),
(16, '16.jpg', '2024-04-28', 'Caption for image 16', 16),
(17, '17.jpg', '2024-04-28', 'Caption for image 17', 17),
(18, '18.jpg', '2024-04-28', 'Caption for image 18', 18),
(19, '19.jpg', '2024-04-28', 'Caption for image 19', 19),
(20, '20.jpg', '2024-04-28', 'Caption for image 20', 20);